---
- name:                 Install seafile beta
  set_fact:
    seafile_tarball_url:  '{{ seafile_tarball_url|replace(".tar.gz", "-beta.tar.gz") }}'
  when:                 seafile_install_version_beta

- name:                 download release tarball
  become:               yes
  become_user:          '{{ seafile_user }}'
  get_url:
    url:                '{{ seafile_tarball_url }}'
    validate_certs:     no
    dest:               '{{ seafile_org_dir + "/installed" }}'
  register:             seafile_tarball_dl
  check_mode:           no

- name:                 untar tarball
  become:               yes
  become_user:          '{{ seafile_user }}'
  unarchive:
    copy:               no
    src:                '{{ seafile_tarball_dl.dest }}'
    dest:               '{{ seafile_org_dir }}'
    creates:            '{{ seafile_distrib_dir }}'
  register:             seafile_tarball_ex

- name:                 check if we already have init scripts
  stat:
    path:               /etc/init.d/{{ item.name }}
  with_items:           '{{ SEAFILE_INIT_SCRIPTS }}'
  when:                 ansible_os_family in item.os_family
  register:             _seafile_init_script_present

- name:                 stop_seafile
  service:
    name:               '{{ item.0.name }}'
    state:              stopped
    sleep:              5
  with_nested:
                        - '{{ SEAFILE_INIT_SCRIPTS }}'
                        - '{{ _seafile_init_script_present.results }}'
  when:
                        - ansible_os_family in item.0.os_family
                        - not item.1 is skipped
                        - item.1.stat.exists
                        - seafile_tarball_dl is changed or seafile_tarball_ex is changed

- name: link latest release
  become:               yes
  become_user:          '{{ seafile_user }}'
  file:
    src:                '{{ seafile_distrib_dir }}'
    dest:               '{{ item }}'
    owner:              '{{ seafile_user }}'
    group:              '{{ seafile_user }}'
    state:              link
  notify:               restart_seafile
  with_items:
                        - '{{ seafile_latest_dir }}'
                        - '{{ seafile_latest2_dir }}'
  register:             seafile_new_release
